// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3TBrRr0fOxUUYfrCI0S_UydB92WaIERc',
    appId: '1:284331232194:web:73ce647734b0e40040e45b',
    messagingSenderId: '284331232194',
    projectId: 'gmaps-616ee',
    authDomain: 'gmaps-616ee.firebaseapp.com',
    storageBucket: 'gmaps-616ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPqZKt-QVsJ_Xp6sF_jQzPuHJ49ucEmEU',
    appId: '1:284331232194:android:043c6eecf287c80940e45b',
    messagingSenderId: '284331232194',
    projectId: 'gmaps-616ee',
    storageBucket: 'gmaps-616ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAcCjAMFyEVH7jBqJMNPQ7i8MaVGbn9_w',
    appId: '1:284331232194:ios:bc9bb657847668b240e45b',
    messagingSenderId: '284331232194',
    projectId: 'gmaps-616ee',
    storageBucket: 'gmaps-616ee.appspot.com',
    iosClientId: '284331232194-0kh9k09pucto0bs9oh9csipcai0333p1.apps.googleusercontent.com',
    iosBundleId: 'com.example.gmapsfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAcCjAMFyEVH7jBqJMNPQ7i8MaVGbn9_w',
    appId: '1:284331232194:ios:bc9bb657847668b240e45b',
    messagingSenderId: '284331232194',
    projectId: 'gmaps-616ee',
    storageBucket: 'gmaps-616ee.appspot.com',
    iosClientId: '284331232194-0kh9k09pucto0bs9oh9csipcai0333p1.apps.googleusercontent.com',
    iosBundleId: 'com.example.gmapsfinal',
  );
}
